---
- name: D01a. Get Policy Data from the firewall
  fortiosconfig:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    action: "get"
    config: "firewall policy"
  register: fw_policy

- name: D01b. Parse policy for locally defined rules
  set_fact:
    defined_policy: |
      [
        {% for policy in fw_policy.meta.results %}
          {
            'rule': '{{ policy.policyid }}',
            {% for rule in rulebase | dict2items %}{% if rule.key | int == policy.policyid | int %}'defined': true,{% endif %}{% endfor %}
          },
        {% endfor %}
      ]

- name: D01c. Parse policy for undefined rules
  set_fact:
    purge_policy: |
      [
        {% for item in defined_policy %}
          {% if item.defined is not defined %}
            '{{ item.rule }}',
          {% endif %}
        {% endfor %}
      ]