---
- name: D04a. Get Service Data from the firewall
  fortiosconfig:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    action: "get"
    config: "firewall.service custom"
  register: fw_service_object

- name: D04b. Parse firewall config for locally defined objects
  set_fact:
    defined_services: |
      [
        {% for object in fw_service_object.meta.results %}
          {
            'name': '{{ object.name }}',
            {% for obj in service_objects_USED_INTERNAL | dict2items %}
              {% if obj.key == object.name %}'defined': 'custom',{% endif %}
            {% endfor %}
            {% for obj in built_in_services | dict2items %}
              {% if obj.key == object.name %}'defined': 'built in',{% endif %}
            {% endfor %}
          },
        {% endfor %}
      ]

- name: D04c. Parse firewall config for unused service objects
  set_fact:
    purge_services: |
      [
        {% for service in defined_services %}
          {% if service.defined is not defined %}
            '{{ service.name }}',
          {% endif %}
        {% endfor %}
      ]