---
- name: E01g. Read list of service objects
  fortiosconfig:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    action: "get"
    config: "firewall.service custom"
  register: fw_service_object

- name: E01h. Parse firewall config for locally defined objects
  set_fact:
    defined_services: |
      [
        {%- for object in fw_service_object.meta.results -%}
          {%- for obj in service_groups_USED_INTERNAL | dict2items -%}
            {%- if obj.key == object.name or (built_in_service_groups | default({}))[object.name] is defined -%}
              '{{ object.name }}',
            {%- endif -%}
          {%- endfor -%}
        {%- endfor -%}
      ]

# Note, this item is LIKELY TO FAIL as objects are likely to only be here if they form part of a policy.
# Blocked on https://github.com/fortinet-solutions-cse/40ansible/issues/40
- name: E01i. Ensure all service objects do not currently have service groups named the same [No-Async]
  fortios_firewall_service_custom:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    firewall_service_custom:
      state: "absent"
      name: "{{ item }}"
  loop: "{{ defined_services }}"
  loop_control:
    label: "{{ item }}"
  when: run_actions_async | default(false) | bool == false

- name: E01i. Ensure all service objects do not currently have service groups named the same (Start) [Async]
  fortios_firewall_service_custom:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    firewall_service_custom:
      state: "absent"
      name: "{{ item }}"
  loop: "{{ defined_services }}"
  loop_control:
    label: "{{ item }}"
  async: 1000
  poll: 0
  changed_when: False
  register: sleeper
  when: run_actions_async | default(false) | bool

- name: E01i. Ensure all service objects do not currently have service groups named the same (Finish) [Async]
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: sleeper_status
  until: sleeper_status.finished
  retries: 500
  delay: 4
  loop: "{{ sleeper.results|flatten(levels=1) }}"
  when: 
  - run_actions_async | default(false) | bool
  - item.ansible_job_id is defined
  loop_control:
    label: "{{ item._ansible_item_label | default(item.item.key | default('Key is missing')) }}"
