---
- name: E01j. Get Service Group Data from the firewall
  fortiosconfig:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    action: "get"
    config: "firewall.service group"
  register: fw_service_group

- name: E01k. Parse firewall config for locally defined objects
  set_fact:
    defined_address_groups: |
      [
        {%- for object in fw_service_group.meta.results -%}
          {%- for obj in service_objects_USED_INTERNAL | dict2items -%}
            {%- if obj.key == object.name or (built_in_services | default({}))[object.name] is defined -%}
              '{{ object.name }}',
            {%- endif -%}
          {%- endfor -%}
        {%- endfor -%}
      ]

# Note, this item is LIKELY TO FAIL as objects are likely to only be here if they form part of a policy.
# Blocked on https://github.com/fortinet-solutions-cse/40ansible/issues/40
- name: E01l. Ensure all service groups do not currently have service objects named the same (Start)
  fortios_firewall_service_group:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    firewall_service_group:
      state: "absent"
      name: "{{ item }}"
  loop: "{{ defined_address_groups }}"
  loop_control:
    label: "{{ item }}"
  async: 1000
  poll: 0
  changed_when: False
  register: sleeper

- name: E01l. Ensure all service groups do not currently have service objects named the same (Finish)
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: sleeper_status
  until: sleeper_status.finished
  retries: 500
  delay: 4
  loop: "{{ sleeper.results|flatten(levels=1) }}"
  when: item.ansible_job_id is defined
  loop_control:
    label: "{{ item._ansible_item_label | default(item.item.key | default('Key is missing')) }}"
