---
- name: E04. Create service objects
  fortios_firewall_service_custom:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    firewall_service_custom:
      state: "present"
      name: "{{ item.key }}"
      comment: "{{ item.value.comment | default(omit) }}"
      protocol: "{% if item.value.tcp | default('') != '' or item.value.udp | default('') != '' -%}
                   TCP/UDP/SCTP
                 {%- elif item.value.icmpcode | default('') != '' and item.value.icmptype | default('') != '' -%}
                   ICMP
                 {%- else -%}
                   IP
                 {%- endif %}"
      tcp-portrange: "{{ item.value.tcp | default(omit) }}"
      udp-portrange: "{{ item.value.udp | default(omit) }}"
      icmpcode: "{{ item.value.icmpcode | default(omit) }}"
      icmptype: "{{ item.value.icmptype | default(omit) }}"
      protocol-number: "{{ item.value.ip | default(omit) }}"
  loop: "{{ service_objects_USED_INTERNAL | dict2items }}"
  loop_control:
    label: "{{ item.key }}"