---
- name: F02a. Check Policy Data on the firewall
  fortiosconfig:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    action: "get"
    config: "firewall policy"
  register: fwpolicy

- name: F02b. Parse firewall policy to confirm ordering
  set_fact:
    desired_policy: |
      [
        {% for policy in fwpolicy.meta.results | sort(attribute='policyid') %}
          {
            'rule': '{{ policy.policyid }}',
            'after': '{{ (loop.previtem | default({}) )['policyid'] | default(0) }}',
            'before': '{{ (loop.nextitem | default({}) )['policyid'] | default(0) }}'
          },
        {% endfor %}
      ]

- name: F02c. Fix Policy Order
  fortiosconfig:
    host: "{{ ansible_host }}"
    username: "{{ admin_username | default(ansible_username | default('admin')) }}"
    password: "{{ admin_password | default(ansible_password | default('')) }}"
    vdom: "{{ ansible_vdom | default('root') }}"
    https: "{{ ansible_https | default(true) }}"
    action: "move"
    config: "firewall policy"
    config_parameters:
      key: "{{ item.rule }}"
      where: "{% if item.after != '0' %}after{% else %}before{% endif %}"
      reference-key: "{% if item.after != '0' %}{{ item.after }}{% else %}{{ item.before }}{% endif %}"
  loop: "{{ desired_policy }}"
  loop_control:
    label: "{{ item.rule }}"
  when: not (item.after == '0' item.before == '0') # This would only happen if there was a single line of policy!
